# File generated by CompCert 3.16
# Command line: -Wall -static -dasm -drtl -o test.o test.c
	.option nopic
	.data
	.balign 8
iters:
	.long	0xf4240, 0x0
	.type	iters, @object
	.size	iters, . - iters
	.text
	.balign 2
	.globl search_for_corruption
search_for_corruption:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -144
	.cfi_adjust_cfa_offset	144
	sd	x30, 0(x2)
	sd	x1, 8(x2)
	.cfi_rel_offset	x1, 8
	sd	x8, 16(x2)
	sd	x9, 24(x2)
	sd	x18, 32(x2)
	sd	x19, 40(x2)
	sd	x20, 48(x2)
	sd	x21, 56(x2)
	sd	x22, 64(x2)
	sd	x23, 72(x2)
	sd	x24, 80(x2)
	sd	x25, 88(x2)
	sd	x26, 96(x2)
	sd	x27, 104(x2)
	j	.L100
.L101:
	mv	x14, x13
	j	.L102
.L103:
	mv	x7, x27
	j	.L104
.L105:
	mv	x28, x17
	j	.L106
.L107:
	mv	x10, x7
	j	.L108
.L109:
	mv	x30, x29
	j	.L110
.L111:
	mv	x12, x11
	j	.L112
.L113:
	mv	x16, x15
	j	.L114
.L115:
	mv	x25, x18
	j	.L116
.L117:
	mv	x6, x5
	j	.L118
.L119:
	mv	x17, x16
	j	.L120
.L121:
	mv	x10, x13
	ld	x8, 16(x2)
	ld	x9, 24(x2)
	ld	x18, 32(x2)
	ld	x19, 40(x2)
	ld	x20, 48(x2)
	ld	x21, 56(x2)
	ld	x22, 64(x2)
	ld	x23, 72(x2)
	ld	x24, 80(x2)
	ld	x25, 88(x2)
	ld	x26, 96(x2)
	ld	x27, 104(x2)
	ld	x1, 8(x2)
	addi	x2, x2, 144
	jr	x1
.L122:
	mv	x13, x11
	j	.L121
.L123:
	bltu	x5, x30, .L124
	j	.L125
.L126:
	mv	x5, x28
	j	.L123
.L127:
	bne	x5, x10, .L126
	j	.L123
.L128:
	mv	x30, x29
	j	.L127
.L129:
	addiw	x31, x0, 255
	bne	x7, x31, .L130
	j	.L131
.L132:
	mv	x7, x6
	j	.L129
.L133:
	mv	x10, x8
	j	.L134
.L135:
	mv	x29, x12
	j	.L136
.L137:
	mv	x17, x12
	j	.L138
.L139:
	mv	x6, x26
	j	.L140
.L141:
	mv	x16, x15
	j	.L142
.L100:
	addiw	x5, x0, 1
	addiw	x29, x0, 1
	addiw	x30, x0, 1
	bne	x30, x5, .L109
.L110:
	sw	x30, 112(x2)
	addiw	x13, x0, 2
	addiw	x15, x0, 2
	addiw	x16, x0, 2
	bne	x16, x13, .L113
.L114:
	sw	x16, 116(x2)
	addiw	x6, x0, 4
	addiw	x17, x0, 4
	addiw	x28, x0, 4
	bne	x28, x6, .L105
.L106:
	sw	x28, 120(x2)
	addiw	x14, x0, 8
	addiw	x5, x0, 8
	addiw	x6, x0, 8
	bne	x6, x14, .L117
.L118:
	sw	x6, 124(x2)
	addiw	x15, x0, 16
	addiw	x7, x0, 16
	addiw	x10, x0, 16
	bne	x10, x15, .L107
.L108:
	sw	x10, 128(x2)
	addiw	x29, x0, 32
	addiw	x11, x0, 32
	addiw	x12, x0, 32
	bne	x12, x29, .L111
.L112:
	sw	x12, 132(x2)
	addiw	x16, x0, 64
	addiw	x13, x0, 64
	addiw	x14, x0, 64
	bne	x14, x16, .L101
.L102:
	sw	x14, 136(x2)
	addiw	x12, x0, 128
	addiw	x16, x0, 128
	addiw	x17, x0, 128
	bne	x17, x12, .L119
.L120:
	sw	x17, 140(x2)
	addiw	x24, x0, 0
	addiw	x20, x0, 0
	addiw	x22, x0, 0
	addiw	x23, x0, 0
	addiw	x19, x0, 0
	addiw	x21, x0, 0
.L143:
	mv	x10, x23
	mv	x28, x19
	mv	x5, x21
	lui	x31, %hi(iters)
	ld	x17, %lo(iters)(x31)
	lui	x31, %hi(iters)
	ld	x29, %lo(iters)(x31)
	lui	x31, %hi(iters)
	ld	x30, %lo(iters)(x31)
	bne	x30, x17, .L128
	j	.L127
.L124:
	lw	x10, 112(x2)
	mv	x11, x10
	mv	x12, x10
	mv	x8, x12
	lw	x14, 116(x2)
	mv	x16, x14
	mv	x15, x14
	mv	x9, x16
	mv	x18, x15
	mv	x25, x14
	lw	x7, 120(x2)
	mv	x14, x7
	mv	x6, x7
	mv	x26, x6
	mv	x6, x7
	lw	x13, 124(x2)
	mv	x28, x13
	mv	x15, x13
	mv	x5, x28
	mv	x27, x15
	mv	x7, x13
	lw	x16, 140(x2)
	mv	x15, x16
	bne	x16, x16, .L141
.L142:
	sw	x16, 112(x2)
	lw	x29, 136(x2)
	mv	x30, x29
	mv	x12, x29
	bne	x29, x30, .L135
.L136:
	sw	x29, 116(x2)
	lw	x17, 132(x2)
	mv	x28, x17
	mv	x12, x17
	bne	x17, x28, .L137
.L138:
	sw	x17, 120(x2)
	lw	x12, 128(x2)
	mv	x13, x12
	sw	x12, 124(x2)
	bne	x7, x5, .L103
.L104:
	sw	x7, 128(x2)
	bne	x6, x14, .L139
.L140:
	sw	x6, 132(x2)
	bne	x25, x9, .L115
.L116:
	sw	x25, 136(x2)
	bne	x10, x11, .L133
.L134:
	sw	x10, 140(x2)
	lw	x5, 112(x2)
	mv	x6, x5
	lw	x7, 116(x2)
	mv	x10, x7
	mv	x11, x7
	lw	x15, 120(x2)
	mv	x29, x15
	mv	x14, x15
	lw	x13, 124(x2)
	mv	x16, x13
	mv	x12, x13
	lw	x8, 128(x2)
	mv	x27, x8
	lw	x18, 132(x2)
	mv	x26, x18
	lw	x28, 136(x2)
	mv	x30, x28
	mv	x17, x28
	lw	x9, 140(x2)
	mv	x25, x9
	xor	x6, x6, x10
	xor	x10, x5, x11
	xor	x11, x5, x7
	xor	x29, x6, x29
	xor	x5, x10, x14
	xor	x6, x11, x15
	xor	x14, x29, x16
	xor	x29, x5, x12
	xor	x11, x6, x13
	xor	x13, x14, x8
	xor	x7, x29, x27
	xor	x6, x11, x8
	xor	x14, x13, x18
	xor	x5, x7, x26
	xor	x29, x6, x18
	xor	x30, x14, x30
	xor	x10, x5, x17
	xor	x5, x29, x28
	xor	x11, x30, x9
	xor	x6, x10, x25
	xor	x7, x5, x9
	bne	x7, x11, .L132
	j	.L129
.L130:
	addiw	x24, x24, 1
	addiw	x20, x20, 1
	addiw	x22, x22, 1
.L131:
	addiw	x23, x23, 1
	addiw	x19, x19, 1
	addiw	x21, x21, 1
	j	.L143
.L125:
	mv	x5, x24
	slli	x5, x5, 32
	srli	x5, x5, 32
	mv	x11, x20
	slli	x11, x11, 32
	srli	x11, x11, 32
	mv	x13, x22
	slli	x13, x13, 32
	srli	x13, x13, 32
	bne	x13, x5, .L122
	j	.L121
	.cfi_endproc
	.type	search_for_corruption, @function
	.size	search_for_corruption, . - search_for_corruption
	.text
	.balign 2
	.globl main
main:
	.cfi_startproc
	mv	x30, x2
	addi	x2, x2, -16
	.cfi_adjust_cfa_offset	16
	sd	x30, 0(x2)
	sd	x1, 8(x2)
	.cfi_rel_offset	x1, 8
	j	.L144
.L145:
	ld	x1, 8(x2)
	addi	x2, x2, 16
	jr	x1
.L146:
	mv	x10, x11
	j	.L145
.L144:
	call	search_for_corruption
	mv	x5, x10
	mv	x7, x5
	mv	x6, x5
	addiw	x12, x7, 0
	addiw	x11, x6, 0
	addiw	x10, x5, 0
	bne	x10, x12, .L146
	j	.L145
	.cfi_endproc
	.type	main, @function
	.size	main, . - main

	.section .note.GNU-stack,"",%progbits
